### ISSUE TITLE
Cant found libraries of tesserrect 

### ISSUE THREAD

**Issue by alienslab10** [halkar/tess-two-xamarin-android-binding#1]
i cant find tesserrect libraries in this code. xamarin studio says The name 'TessBaseApi' doest not exist in the current context. what is this error kindly help. 

using Com.Googlecode.Leptonica.Android;
using Com.Googlecode.Tesseract.Android;
cant find these.

**Comment by halkar** [comment]
Sorry, my bad. .gitignore removed these files. Added files now.

**Comment by alienslab10** [comment]
Thanks buddy. And its OK ☺
